kind: pipeline
name: default

environment:
  APP_ENV: "local"
  APP_KEY: helloworlddlrowolleh
  DB_CONNECTION: ":memory:"
  JWT_SECRET: "pXj0Wh0QIz09mfaMAfUjSnELPDHhaDn4R4jN3fuuvCynDY3XiaMSh6BqbgP8CRCL"

steps:
  - name: Install
    image: composer
    commands:
      - cd backend/
      - composer install

  - name: Linter
    image: php:8.0.2
    commands:
      - cd backend/
      - vendor/bin/tlint

  - name: Test
    image: php:8.0.2
    commands:
      - pecl install xdebug --quiet 1> /dev/null 2>&1 && docker-php-ext-enable xdebug
      - cd backend/
      - vendor/bin/phpunit --configuration phpunit.xml --coverage-html .reports
