kind: pipeline
name: default

environment:
  APP_ENV: local
  DB_CONNECTION: sqlite

steps:
  - name: Install
    image: composer
    commands:
      - cd src/
      - composer install

  - name: Linter
    image: php:7.4
    commands:
      - cd src/
      - vendor/bin/tlint --quiet

  - name: Test
    image: php:7.4
    commands:
      - pecl install xdebug && docker-php-ext-enable xdebug
      - cd src/
      - vendor/bin/phpunit --configuration phpunit.xml --coverage-html .reports