kind: pipeline
name: default

environment:
  APP_ENV: local
  DB_CONNECTION: sqlite

steps:
  - name: Install
    image: composer
    commands:
      - cd backend/
      - composer install

  - name: Linter
    image: php:7.4
    commands:
      - cd backend/
      - vendor/bin/tlint

  - name: Test
    image: php:7.4
    commands:
      - pecl install xdebug --quiet 1> /dev/null 2>&1 && docker-php-ext-enable xdebug
      - cd backend/
      - vendor/bin/phpunit --configuration phpunit.xml --coverage-html .reports
