version: "3"

volumes:
  db:
  logs:

networks:
  front:
  back:

services:
  nginx:
    image: leaguetables/nginx:v1
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    depends_on:
      - backend
      - frontend
    networks:
      - front
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html/api
      - ./frontend/public:/var/www/html/frontend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  frontend:
    image: leaguetables/frontend:v1
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    expose:
      - 8080
    networks:
      - front
    volumes:
      - ./frontend:/app

  backend:
    image: leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leaguetables
      - DB_USERNAME=leaguetables
      - DB_PASSWORD=helloworld
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 9000
    networks:
      - front
      - back
    volumes:
      - ./backend:/var/www/html/api
      - logs:/var/www/html/api/storage/logs

#  worker:
#    image: leaguetables/backend:v1
#    command: be a worker
#    build:
#      context: .
#      dockerfile: docker/backend/Dockerfile
#    working_dir: /var/www/html
#    environment:
#      CONTAINER_ROLE: queue
#    depends_on:
#      - redis
#      - db
#    labels:
#      - "traefik.enable=false"
#
#  scheduler:
#    image: leaguetables/backend:v1
#    command: be a scheduler
#    build:
#      context: .
#      dockerfile: docker/backend/Dockerfile
#    depends_on:
#      - redis
#      - db

  db:
    image: linuxserver/mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=helloworld
      - TZ=Europe/London
      - MYSQL_DATABASE=leaguetables
      - MYSQL_USER=leaguetables
      - MYSQL_PASSWORD=helloworld
    volumes:
      - db:/config
    networks:
      - back
    ports:
      - 3306:3306

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - back
