version: "3"

volumes:
  db:
  logs:

services:
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    depends_on:
      - backend
      - frontend
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./backend:/var/www/html/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: app
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leaguetables
      - DB_USERNAME=leaguetables
      - DB_PASSWORD=helloworld
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ADMIN_USERNAME=ethan
      - ADMIN_PASSWORD=cotterell
      - JWT_SECRET=OeBlqZryMt0ga7PtsO79vQz2CFEIBXjblMKUpjNNJAsR0KxDPHQREDLnp5KYkR3l
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html/api
      - logs:/var/www/html/api/storage/logs:rw
      - ./docker/backend/import:/import:ro

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.development
    environment:
      - VUE_APP_LEAGUE_NAME=Rutland and Stamford
      - VUE_APP_API_URL=http://127.0.0.1/api
      - NODE_ENV=production
    ports:
      - "127.0.0.1:8080:80"
    volumes:
    - ./frontend/public:/app/public
    - ./frontend/src:/app/src
    - ./frontend/babel.config.js:/app/babel.config.js
    - ./frontend/package.json:/app/package.json
    - ./frontend/vue.config.js:/app/vue.config.js

  db:
    image: linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=helloworld
      - TZ=Europe/London
      - MYSQL_DATABASE=leaguetables
      - MYSQL_USER=leaguetables
      - MYSQL_PASSWORD=helloworld
    volumes:
      - db:/config
    expose:
      - 3306

  redis:
    image: redis
    expose:
      - 6379

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 127.0.0.1:8888:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=helloworld

  backend-test:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    tty: true
    stdin_open: true
    entrypoint: sh
    command: -c "cd /var/www/html/api && ./vendor/bin/phpunit"
    environment:
      - DB_CONNECTION=sqlite
      - "DB_DATABASE=/database.testing.sqlite"
#      - "DB_DATABASE=:memory:"
      - APP_DEBUG=true
      - APP_ENV=testing
      - JWT_SECRET=your-secret-key-here
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html/api
      - logs:/var/www/html/api/storage/logs
      - ./docker/backend/import:/import:ro
      - ./docker/backend/database.testing.sqlite:/database.testing.sqlite