version: "3"

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/database
      o: bind
  code:
    driver: local
    driver_opts:
      type: none
      device: $PWD/backend
      o: bind
  kanboard_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/kanboard/data
      o: bind

  kanboard_plugins:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/kanboard/plugins
      o: bind

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - code:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/sites:/etc/nginx/sites-available

  backend:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - db
    volumes:
      - code:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

  db:
    image: linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=helloworld
      - TZ=Europe/London
      - MYSQL_DATABASE=leaguetables
      - MYSQL_USER=leaguetables
      - MYSQL_PASSWORD=helloworld
    volumes:
      - db:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  redis:
    image: redis
    expose:
      - 6379

  worker:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: php artisan queue:work
    depends_on:
      - redis
      - db
    working_dir: /usr/share/nginx/html

###
### Development containers
###
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=helloworld

  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8888:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins