version: "3"

volumes:
  db:
  logs:

services:
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leaguetables
      - DB_USERNAME=leaguetables
      - DB_PASSWORD=helloworld
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html/api
      - logs:/var/www/html/api/storage/logs:rw

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.development
    depends_on:
      - nginx
      - backend
    ports:
      - "8080:8080"
    volumes:
    - ./frontend/public:/app/public
    - ./frontend/src:/app/src
    - ./frontend/babel.config.js:/app/babel.config.js

  db:
    image: linuxserver/mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=helloworld
      - TZ=Europe/London
      - MYSQL_DATABASE=leaguetables
      - MYSQL_USER=leaguetables
      - MYSQL_PASSWORD=helloworld
    volumes:
      - db:/config
    expose:
      - 3306

  redis:
    image: redis
    expose:
      - 6379

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=helloworld

  backend-test:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    tty: true
    stdin_open: true
    command: sh -c "cd /var/www/html/api && ./vendor/bin/phpunit"
    environment:
      - DB_CONNECTION=sqlite
      - "DB_DATABASE=:memory:"
      - APP_DEBUG=true
      - APP_ENV=testing
    expose:
      - 9000
    volumes:
      - ./backend:/var/www/html/api
      - logs:/var/www/html/api/storage/logs