version: "3"

services:
  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/sites:/etc/nginx/sites-available
  php:
    image: php:fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./src:/usr/share/nginx/html
