version: "3"

services:
#  phpmyadmin:
#    image: phpmyadmin
#    depends_on:
#      - db
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_USER=root
#      - PMA_PASSWORD=helloworld

  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - 8888:80
    volumes:
      - ./volumes/kanboard/data:/var/www/app/data
      - ./volumes/kanboard/plugins:/var/www/app/plugins