version: "3"

volumes:
  db:
  logs:

networks:
  front:
  back:

services:
  nginx:
    image: leaguetables/nginx:v1
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    depends_on:
      - backend
      - frontend
    networks:
      - front
      - back
    ports:
      - "80:80"

  frontend:
    image: leaguetables/frontend:v1
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    environment:
      - VUE_APP_API_URL=https://badminton.ethancotterell.co.uk/api
      - NODE_ENV=production
    expose:
      - 80
    networks:
      - back

  backend:
    image: leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: app
    depends_on:
      - redis
      - db
    environment:
      - APP_NAME=LeagueTables
      - APP_ENV=prod
      - APP_KEY=helloworld
      - APP_DEBUG=false
      - APP_URL=https://badminton.ethancotterell.co.uk
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - QUEUE_DRIVER=redis
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leaguetables
      - DB_USERNAME=leaguetables
      - DB_PASSWORD=helloworld
      - REDIS_CLIENT=predis
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=pXj0Wh0QIz09mfaMAfUjSnELPDHhaDn4R4jN3fuuvCynDY3XiaMSh6BqbgP8CRCL
    expose:
      - 9000
    networks:
      - back
    volumes:
      - logs:/var/www/html/api/storage/logs
      - ./docker/backend/import:/import:ro

  worker:
    image: registry.ethancotterell.co.uk/leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: worker
    environment:
      - APP_NAME=LeagueTables
      - APP_ENV=prod
      - APP_KEY=helloworld
      - APP_DEBUG=false
      - APP_URL=https://badminton.ethancotterell.co.uk
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - QUEUE_DRIVER=redis
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leaguetables
      - DB_USERNAME=leaguetables
      - DB_PASSWORD=helloworld
      - REDIS_CLIENT=predis
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=pXj0Wh0QIz09mfaMAfUjSnELPDHhaDn4R4jN3fuuvCynDY3XiaMSh6BqbgP8CRCL
    depends_on:
      - redis
      - db
    networks:
      - back
    volumes:
      - logs:/var/www/html/api/storage/logs

  scheduler:
    image: registry.ethancotterell.co.uk/leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: scheduler
    environment:
      - APP_NAME=LeagueTables
      - APP_ENV=prod
      - APP_KEY=helloworld
      - APP_DEBUG=false
      - APP_URL=https://badminton.ethancotterell.co.uk
      - APP_TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - QUEUE_DRIVER=redis
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=leaguetables
      - DB_USERNAME=leaguetables
      - DB_PASSWORD=helloworld
      - REDIS_CLIENT=predis
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=pXj0Wh0QIz09mfaMAfUjSnELPDHhaDn4R4jN3fuuvCynDY3XiaMSh6BqbgP8CRCL
    depends_on:
      - redis
      - db
    networks:
      - back
    volumes:
      - logs:/var/www/html/api/storage/logs

  db:
    image: linuxserver/mariadb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=helloworld
      - TZ=Europe/London
      - MYSQL_DATABASE=leaguetables
      - MYSQL_USER=leaguetables
      - MYSQL_PASSWORD=helloworld
    volumes:
      - db:/config
    networks:
      - back
    ports:
      - 3306:3306

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=helloworld
    networks:
      - back
