version: "3"

volumes:
  db:
  logs:

networks:
  front:
  back:

services:
  nginx:
    image: leaguetables/nginx:v1
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    depends_on:
      - backend
      - frontend
    networks:
      - front
      - back
    ports:
      - "80:80"

  frontend:
    image: leaguetables/frontend:v1
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - 80
    networks:
      - back

  backend:
    image: leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: app
    depends_on:
      - redis
      - db
    env_file:
      - .env
    expose:
      - 9000
    networks:
      - back
    volumes:
      - logs:/var/www/html/api/storage/logs
      - ./docker/backend/import:/import:ro

  worker:
    image: registry.ethancotterell.co.uk/leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: worker
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - back
    volumes:
      - logs:/var/www/html/api/storage/logs

  scheduler:
    image: registry.ethancotterell.co.uk/leaguetables/backend:v1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: scheduler
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - back
    volumes:
      - logs:/var/www/html/api/storage/logs

  db:
    image: linuxserver/mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/config
    networks:
      - back
    expose:
      - 3306

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=helloworld
    networks:
      - back
