# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY frontend/package.json /app/package.json
COPY frontend/package-lock.json /app/package-lock.json
RUN npm install
RUN npm install @vue/cli@3.7.0 -g

COPY frontend/ /app

# start app
CMD ["npm", "run", "serve"]
